apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm3-chart.fullname" . }}
  labels:
    {{- include "helm3-chart.labels" . | nindent 4 }} 
data:
  mongodb.host: {{ .Release.Name }}-mongodb
  mongodb.port: "27017"
  mongodb.database: arch
  mongodb.authentication-database: arch
  application.name: Architector by AEuegene
  server.port: "80"