apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm3-chart.fullname" . }}
  labels:
    {{- include "helm3-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm3-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm3-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "helm3-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SPRING_DATA_MONGODB_PORT
            valueFrom:
             configMapKeyRef:
                name: {{ include "helm3-chart.fullname" . }}
                key: mongodb.port
          - name: SPRING_DATA_MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm3-chart.fullname" . }}
                key: mongodb.host
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm3-chart.fullname" . }}
                key: mongodb.database
          - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm3-chart.fullname" . }}
                key: mongodb.authentication-database
          - name: SPRING_DATA_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "helm3-chart.fullname" . }}-secrets
                key: mongodb.username
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "helm3-chart.fullname" . }}-secrets
                key: mongodb.password
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm3-chart.fullname" . }}
                key: server.port
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
