apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  serviceName: "mongodb"
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: aristoveugene/aeuge:arch-02-db
          volumeMounts:
            - mountPath: /data/db
              name: mongodbstorage
            - mountPath: /etc/timezone
              name: timezone
            - mountPath: /etc/localtime
              name: localtime
          ports:
            - name: mongodb
              containerPort: 27017  
        - name: mongodb-exporter
          image: bitnami/mongodb-exporter:latest
          ports:
            - name: mongodb-exp
              containerPort: 9216  
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
  volumeClaimTemplates:
    - metadata:
        name: mongodbstorage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - name: app
      port: 80
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: aristoveugene/aeuge:arch-03-app
          volumeMounts:
            - mountPath: /etc/timezone
              name: timezone
            - mountPath: /etc/localtime
              name: localtime
          ports:
            - name: app
              containerPort: 80
          env:
          - name: SPRING_DATA_MONGODB_PORT
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.port
          - name: SPRING_DATA_MONGODB_HOST
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.host
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.database
          - name: SERVER_PORT
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: server.port
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime