apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: app
    path: /monitor/prometheus
    interval: 5s