spring:
    banner:
      location: banner.txt
    data.mongodb:
      host: localhost
      port: 27017
      database: arch
      username: mongo
      password : mongo
      authentication-database: admin
    application:
      name: Architector by AEuegene
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
      base-path: /monitor
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
jwt:
  secret: GLSpLFMvoisd
  tokenttl: 100