apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: aristoveugene/aeuge:arch-02-db
          volumeMounts:
            - mountPath: /data/db
              name: mongodbpath
          ports:
            - containerPort: 27017  
              name: mongodb
      volumes:
        - name: mongodbpath
          hostPath:
            path: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 80
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: aristoveugene/aeuge:arch-02-app
          ports:
            - containerPort: 80
              name: app
          env:
          - name: SPRING_DATA_MONGODB_PORT
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.port
          - name: SPRING_DATA_MONGODB_HOST
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.host
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: mongodb.database
          - name: SERVER_PORT
            valueFrom:
             configMapKeyRef:
                name: app-configmap
                key: server.port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: app
    servicePort: 80